# This workflow will trigger container security scans in the pipeline

name: Run Container Scans

on: 
    push:
        branches:
          - release/prod

jobs:
    container-sec:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build the Container Image
              run: docker build . --file Dockerfile --tag localbuild/testimage:latest

            - name: Scan Image with Checkmarx
              uses: checkmarx/ast-github-action@main
              with:
                  project_name: test
                  cx_tenant: ${{ vars.CX_TENANT_NAME }}
                  base_uri: ${{ vars.CX_TENANT_URL }}
                  cx_client_id: ${{ vars.CX_CLIENT_ID }}
                  cx_client_secret: ${{ secrets.CX_TOKEN }}
        continue-on-error: true
